# Production Kubernetes Slack Bot
#
# A multi-tenant AgentFlow that responds to Slack messages in the #production
# channel and connects to the production Kubernetes cluster.
#
# Key Features:
# - Filtered to specific channels (#production, #prod-alerts)
# - Uses production kubeconfig
# - Restricted to approved users/groups
# - Safe kubectl commands only (read + approved mutations)
#
# Prerequisites:
# - Production kubeconfig at ~/.kube/prod-config or KUBECONFIG_PROD env var
# - SLACK_BOT_TOKEN and SLACK_SIGNING_SECRET
# - LLM API key (ANTHROPIC_API_KEY, OPENAI_API_KEY, or GOOGLE_API_KEY)
#
# To deploy:
#   aofctl apply -f examples/flows/multi-tenant/slack-prod-k8s-bot.yaml
#
# Then start the server with flows directory:
#   aofctl serve --flows-dir examples/flows/multi-tenant --port 3000

apiVersion: aof.dev/v1
kind: AgentFlow
metadata:
  name: slack-prod-k8s-bot
  labels:
    platform: slack
    environment: production
    cluster: prod-cluster
    team: platform-engineering
  annotations:
    description: "Production K8s bot for #production channel"
    owner: platform-team@company.com

spec:
  # Slack trigger with channel filtering
  trigger:
    type: Slack
    config:
      events:
        - app_mention       # @k8s-bot mentions
        - message           # Direct messages
      # Only respond in production channels
      channels:
        - production
        - prod-alerts
        - sre-oncall
      # Optional: restrict to specific users/groups
      users:
        - U012PLATFORM1   # Platform team lead
        - U012PLATFORM2   # SRE team
      # Optional: pattern matching for keywords
      patterns:
        - "^(kubectl|k8s|kubernetes|pod|deploy|scale)"
        - "prod(uction)?"
      bot_token: ${SLACK_BOT_TOKEN}
      signing_secret: ${SLACK_SIGNING_SECRET}

  # Production execution context
  context:
    # Production kubeconfig
    kubeconfig: ${KUBECONFIG_PROD:-~/.kube/prod-config}
    # Default namespace for production
    namespace: default
    # Cluster name (for logging/auditing)
    cluster: prod-cluster
    # Environment variables available to agents
    env:
      ENVIRONMENT: production
      CLUSTER_NAME: prod-cluster
      LOG_LEVEL: info
      # Safety settings
      KUBECTL_READONLY: "false"
      REQUIRE_APPROVAL: "true"
    # Working directory for commands
    working_dir: /workspace

  # Workflow nodes
  nodes:
    # 1. Parse and validate the incoming message
    - id: parse-message
      type: Transform
      config:
        script: |
          # Extract message details from Slack event
          export MESSAGE_TEXT="${event.text}"
          export SLACK_USER="${event.user}"
          export SLACK_CHANNEL="${event.channel}"
          export SLACK_TIMESTAMP="${event.ts}"
          # Log for audit trail
          echo "[PROD] User: ${SLACK_USER}, Channel: ${SLACK_CHANNEL}"

    # 2. Process with production K8s agent
    - id: agent-process
      type: Agent
      config:
        # Reference to the agent config file
        agent: kubernetes-ops-agent
        # Pass the user message
        input: ${MESSAGE_TEXT}
        # Context passed to agent
        context:
          slack_channel: ${SLACK_CHANNEL}
          slack_user: ${SLACK_USER}
          environment: production
          cluster: prod-cluster

    # 3. Send response back to Slack
    - id: send-response
      type: Slack
      config:
        channel: ${SLACK_CHANNEL}
        thread_ts: ${SLACK_TIMESTAMP}
        message: |
          ${agent-process.output.output}

  # Flow connections
  connections:
    - from: trigger
      to: parse-message
    - from: parse-message
      to: agent-process
    - from: agent-process
      to: send-response

  # Global flow configuration
  config:
    default_timeout_seconds: 120
    verbose: true
    retry:
      max_attempts: 2
      initial_delay: "2s"
      backoff_multiplier: 2.0
