# Development Local Cluster Slack Bot
#
# A multi-tenant AgentFlow for local development clusters (minikube, kind, etc.)
# Responds to messages in #dev-local channel and connects to local cluster.
#
# Key Features:
# - Filtered to #dev-local channel
# - Uses local kubeconfig (minikube, kind, docker-desktop)
# - Full permissions for development testing
# - Fast iteration with minimal restrictions
#
# Prerequisites:
# - Local Kubernetes cluster running (minikube, kind, docker-desktop)
# - SLACK_BOT_TOKEN and SLACK_SIGNING_SECRET
# - LLM API key
#
# To deploy:
#   aofctl apply -f examples/flows/multi-tenant/slack-dev-local-bot.yaml
#
# Start server:
#   aofctl serve --flows-dir examples/flows/multi-tenant --port 3000

apiVersion: aof.dev/v1
kind: AgentFlow
metadata:
  name: slack-dev-local-bot
  labels:
    platform: slack
    environment: development
    cluster: local
    team: development
  annotations:
    description: "Local dev cluster bot for experimentation"
    owner: dev@company.com

spec:
  trigger:
    type: Slack
    config:
      events:
        - app_mention
        - message
      # Development channels only
      channels:
        - dev-local
        - sandbox
        - playground
      # No user restrictions - open for all devs
      users: []
      # Match any k8s-related command
      patterns:
        - ".*"  # Match everything in dev channels
      bot_token: ${SLACK_BOT_TOKEN}
      signing_secret: ${SLACK_SIGNING_SECRET}

  # Local development context
  context:
    # Local kubeconfig (defaults to ~/.kube/config)
    kubeconfig: ${KUBECONFIG:-~/.kube/config}
    # Default namespace
    namespace: default
    # Local cluster identifier
    cluster: local
    env:
      ENVIRONMENT: development
      CLUSTER_NAME: local
      LOG_LEVEL: debug
      # Full permissions in local dev
      KUBECTL_READONLY: "false"
      REQUIRE_APPROVAL: "false"
      ALLOW_DELETE: "true"
      ALLOW_EXEC: "true"
      # Verbose output for debugging
      OUTPUT_FORMAT: verbose
    working_dir: /workspace

  nodes:
    - id: parse-message
      type: Transform
      config:
        script: |
          export MESSAGE_TEXT="${event.text}"
          export SLACK_USER="${event.user}"
          export SLACK_CHANNEL="${event.channel}"
          export SLACK_TIMESTAMP="${event.ts}"
          echo "[LOCAL-DEV] User: ${SLACK_USER}"

    - id: agent-process
      type: Agent
      config:
        agent: kubernetes-ops-agent
        input: ${MESSAGE_TEXT}
        context:
          slack_channel: ${SLACK_CHANNEL}
          slack_user: ${SLACK_USER}
          environment: development
          cluster: local
          # Full permissions
          allow_delete: "true"
          allow_exec: "true"
          allow_apply: "true"

    - id: send-response
      type: Slack
      config:
        channel: ${SLACK_CHANNEL}
        thread_ts: ${SLACK_TIMESTAMP}
        message: |
          :computer: **[LOCAL-DEV]**
          ${agent-process.output.output}

  connections:
    - from: trigger
      to: parse-message
    - from: parse-message
      to: agent-process
    - from: agent-process
      to: send-response

  config:
    default_timeout_seconds: 300  # Longer timeout for dev
    verbose: true
    retry:
      max_attempts: 1  # No retries in dev
      initial_delay: "1s"
      backoff_multiplier: 1.0
