# Code Review Team Fleet
#
# A fleet combining security scanning and K8s operations for comprehensive code reviews.
# Demonstrates agent composition using ref: syntax.
#
# Usage:
#   aofctl apply -f fleets/code-review-team.yaml
#   aofctl run fleet code-review-team "review deployment manifest"

apiVersion: aof.dev/v1alpha1
kind: Fleet
metadata:
  name: code-review-team
  labels:
    category: development
    purpose: code-review

spec:
  description: "Security scanner + K8s ops for comprehensive code and manifest reviews"
  
  # Reference agents from agents/ directory
  agents:
    - ref: agents/security.yaml
    - ref: agents/k8s-ops.yaml
  
  # Fleet-level coordination
  coordination:
    strategy: collaborative
    # Security agent reviews first, then K8s agent validates deployment
    workflow:
      - agent: security
        role: lead
        tasks:
          - scan_code
          - check_dependencies
          - validate_configs
      - agent: k8s-ops
        role: validator
        tasks:
          - validate_manifests
          - check_resource_limits
          - verify_security_contexts
