# Code Review Team Fleet
#
# A fleet combining security scanning and K8s operations for comprehensive code reviews.
# Demonstrates agent composition using ref: syntax.
#
# Usage:
#   aofctl apply -f fleets/code-review-team.yaml
#   aofctl run fleet code-review-team "review deployment manifest"

apiVersion: aof.dev/v1
kind: AgentFleet
metadata:
  name: code-review-team
  labels:
    category: development
    purpose: code-review

spec:
  agents:
    - name: security-reviewer
      role: specialist
      config: agents/security.yaml

    - name: k8s-validator
      role: validator
      config: agents/k8s-ops.yaml

  coordination:
    mode: tiered
    distribution: round-robin
    tiered:
      tiers:
        "1":
          agents: [security-reviewer]
          consensus:
            strategy: unanimous
        "2":
          agents: [k8s-validator]
          consensus:
            strategy: unanimous
