# Production Context with Telegram Platform Policy
#
# This context demonstrates strict safety controls for production clusters
# accessed via Telegram mobile companion.
#
# Policy:
# - Telegram: Block delete/dangerous, require approval for writes
# - Slack: Require approval for delete/dangerous
# - CLI: Full access (trusted)

apiVersion: aof.dev/v1
kind: Context
metadata:
  name: prod
  labels:
    environment: production
    tier: critical

spec:
  namespace: production
  cluster: prod-cluster

  # Default agent for this context (read-only for safety)
  default_agent: k8s-status

  # Platform-specific policies
  platform_policies:
    # Telegram: Most restrictive (mobile, less trusted)
    telegram:
      blocked_classes:
        - delete
        - dangerous
      approval_classes:
        - write
      allowed_classes:
        - read
      blocked_message: |
        This operation is blocked on Telegram for production.
        Use Slack or kubectl directly for write/delete operations.

    # Slack: Moderate (desktop, more trusted)
    slack:
      blocked_classes:
        - dangerous
      approval_classes:
        - delete
        - write
      allowed_classes:
        - read
      approval_timeout_minutes: 30

    # WhatsApp: Read-only (similar to Telegram)
    whatsapp:
      blocked_classes:
        - delete
        - dangerous
        - write
      approval_classes: []
      allowed_classes:
        - read
      blocked_message: |
        WhatsApp is read-only for production.
        Use Slack for any modifications.

    # CLI: Full access (trusted, authenticated)
    cli:
      blocked_classes: []
      approval_classes: []
      allowed_classes:
        - read
        - write
        - delete
        - dangerous

  # Users who can approve operations
  approval_allowed_users:
    - "@oncall"
    - "sre-team"

  # Additional safety settings
  safety:
    require_confirmation_for_namespace:
      - production
      - kube-system
    max_resources_per_operation: 10
    audit_all_operations: true
