# PagerDuty Incident Bot Binding
#
# Automatic incident response triggered by PagerDuty alerts.

apiVersion: aof.dev/v1
kind: Binding
metadata:
  name: pagerduty-incident
  labels:
    environment: production
    platform: pagerduty
    capability: incident-response

spec:
  trigger:
    ref: triggers/pagerduty.yaml

  flow:
    ref: flows/incident-flow.yaml

  context:
    ref: contexts/prod.yaml

  # Automated response for PagerDuty alerts
  overrides:
    # Auto-investigate, but still require approval for remediation
    auto_investigate: true
    approval:
      required_for_remediation: true
      notification_channels:
        - slack: "#prod-alerts"
        - pagerduty: "platform-oncall"
