# Production Slack K8s Bot Binding
#
# Ties together:
#   - Trigger: Slack production channels
#   - Flow: K8s operations workflow
#   - Context: Production cluster configuration
#
# This creates a complete working bot for production K8s operations via Slack.

apiVersion: aof.dev/v1
kind: Binding
metadata:
  name: prod-slack-k8s
  labels:
    environment: production
    platform: slack
    capability: kubernetes

spec:
  # Message source
  trigger:
    ref: triggers/slack-prod.yaml

  # Orchestration logic
  flow:
    ref: flows/k8s-ops-flow.yaml

  # Environment configuration
  context:
    ref: contexts/prod.yaml

  # Optional: Override specific settings
  overrides:
    approval:
      # Extra strict for production
      require_double_approval: true
      approval_timeout_seconds: 600
