# Staging Slack K8s Bot Binding
#
# Same flow as production, but with staging trigger and context.
# Demonstrates multi-environment pattern.

apiVersion: aof.dev/v1
kind: Binding
metadata:
  name: staging-slack-k8s
  labels:
    environment: staging
    platform: slack
    capability: kubernetes

spec:
  trigger:
    ref: triggers/slack-staging.yaml

  flow:
    ref: flows/k8s-ops-flow.yaml  # Same flow, different env

  context:
    ref: contexts/staging.yaml

  # Staging is more permissive
  overrides:
    approval:
      require_double_approval: false
      approval_timeout_seconds: 180
