# Test configuration for real MCP servers
# Use with: aofctl run agent examples/test-mcp-servers.yaml --input "list kubernetes pods"

apiVersion: aof.dev/v1
kind: Agent
metadata:
  name: k8s-ops-agent
  labels:
    test: mcp-servers

spec:
  model: google:gemini-2.5-flash

  instructions: |
    You are a Kubernetes operations assistant with access to kubectl tools.
    Help users manage their Kubernetes clusters using the available MCP tools.
    Always explain what you're doing before executing commands.

  mcp_servers:
    # kubectl-ai MCP server (local binary)
    - name: kubectl-ai
      transport: stdio
      command: kubectl-ai
      args:
        - "--mcp-server"
        - "--mcp-server-mode=stdio"
      timeout_secs: 120
      auto_reconnect: true

  max_iterations: 10
  temperature: 0.3

---
# GitHub operations agent
apiVersion: aof.dev/v1
kind: Agent
metadata:
  name: github-ops-agent

spec:
  model: google:gemini-2.5-flash

  instructions: |
    You are a GitHub assistant. Help users manage repositories, issues, and PRs.

  mcp_servers:
    # GitHub MCP server (Docker)
    - name: github
      transport: stdio
      command: docker
      args:
        - "run"
        - "-i"
        - "--rm"
        - "-e"
        - "GITHUB_PERSONAL_ACCESS_TOKEN"
        - "ghcr.io/github/github-mcp-server"
      env:
        GITHUB_PERSONAL_ACCESS_TOKEN: "${GITHUB_TOKEN}"
      timeout_secs: 60

  max_iterations: 15
  temperature: 0.5

---
# Multi-tool agent with Prometheus monitoring
apiVersion: aof.dev/v1
kind: Agent
metadata:
  name: sre-agent

spec:
  model: google:gemini-2.5-flash

  instructions: |
    You are an SRE assistant with access to Kubernetes and Prometheus monitoring.
    Help users diagnose issues and monitor their infrastructure.

  mcp_servers:
    # kubectl-ai for Kubernetes operations
    - name: kubectl-ai
      transport: stdio
      command: kubectl-ai
      args:
        - "--mcp-server"
        - "--mcp-server-mode=stdio"
      timeout_secs: 120

    # Prometheus MCP server (Docker) - requires Prometheus running
    - name: prometheus
      transport: stdio
      command: docker
      args:
        - "run"
        - "-i"
        - "--rm"
        - "-e"
        - "PROMETHEUS_URL"
        - "ghcr.io/pab1it0/prometheus-mcp-server:latest"
      env:
        PROMETHEUS_URL: "http://host.docker.internal:9090"
      timeout_secs: 60
      auto_reconnect: false

  max_iterations: 20
  temperature: 0.3

---
# Filesystem agent using official MCP server
apiVersion: aof.dev/v1
kind: Agent
metadata:
  name: filesystem-agent

spec:
  model: google:gemini-2.5-flash

  instructions: |
    You are a file system assistant. Help users explore and manage files.

  mcp_servers:
    - name: filesystem
      transport: stdio
      command: npx
      args:
        - "-y"
        - "@modelcontextprotocol/server-filesystem"
        - "/tmp"
      timeout_secs: 30

  max_iterations: 10
  temperature: 0.5
