# PagerDuty Webhook Trigger
#
# Receives PagerDuty incident webhooks and routes to incident flow.

apiVersion: aof.dev/v1
kind: Trigger
metadata:
  name: pagerduty-incidents
  labels:
    platform: pagerduty
    purpose: incidents

spec:
  type: PagerDuty
  config:
    # Webhook endpoint
    path: /webhook/pagerduty

    # Authentication
    webhook_secret: ${PAGERDUTY_WEBHOOK_TOKEN}

    # PagerDuty service IDs to monitor
    service_ids:
      - PXXXXXX  # Production platform
      - PYYYYYY  # Production database

  # Route PagerDuty events to flows/agents
  # Event types act as virtual "commands"
  commands:
    incident.triggered:
      flow: incident-flow
      description: "Auto-triggered incident response"

    incident.acknowledged:
      agent: devops
      description: "Incident acknowledged"

  default_agent: devops
