# Production Slack Trigger
#
# Complete Slack configuration for production environment.
# Includes command bindings - no separate Binding CRD needed.
#
# Usage in daemon.yaml:
#   triggers:
#     directory: ./examples/triggers/

apiVersion: aof.dev/v1
kind: Trigger
metadata:
  name: slack-prod
  labels:
    platform: slack
    environment: production

spec:
  type: Slack
  config:
    # Event types to listen for
    events:
      - app_mention       # @bot-name mentions
      - message           # Direct messages

    # Only respond in production channels
    channels:
      - production
      - prod-alerts
      - sre-oncall

    # Optional: restrict to specific users
    # users:
    #   - U012PLATFORM1   # Platform team lead
    #   - U012PLATFORM2   # SRE team

    # Authentication (env var references)
    bot_token: ${SLACK_BOT_TOKEN}
    signing_secret: ${SLACK_SIGNING_SECRET}

  # Command bindings for this trigger
  # Maps /command to agent, fleet, or flow
  commands:
    /aof:
      agent: devops
      description: "General DevOps assistant"

    /diagnose:
      fleet: rca-fleet
      description: "Root cause analysis with multi-model consensus"

    /k8s:
      agent: k8s-ops
      description: "Kubernetes cluster operations"

    /aws:
      agent: aws-agent
      description: "AWS cloud operations"

    /docker:
      agent: docker-ops
      description: "Container management"

    /deploy:
      flow: deploy-flow
      description: "Deployment workflow with approvals"

  # Default agent for @mentions and natural language
  default_agent: devops
