# Staging Slack Trigger
#
# Slack configuration for staging/dev environment.
# More permissive than production.

apiVersion: aof.dev/v1
kind: Trigger
metadata:
  name: slack-staging
  labels:
    platform: slack
    environment: staging

spec:
  type: Slack
  config:
    events:
      - app_mention
      - message

    # Staging channels
    channels:
      - staging
      - staging-alerts
      - qa-testing

    # Authentication
    bot_token: ${SLACK_BOT_TOKEN}
    signing_secret: ${SLACK_SIGNING_SECRET}

  # Command bindings (same as prod, but more relaxed)
  commands:
    /aof:
      agent: devops
      description: "General DevOps assistant"

    /k8s:
      agent: k8s-ops
      description: "Kubernetes operations"

    /deploy:
      flow: deploy-flow
      description: "Deploy to staging"

  default_agent: devops
