# On-Call Telegram Trigger
#
# Complete Telegram configuration for on-call incident response.
# Includes command bindings - no separate Binding CRD needed.

apiVersion: aof.dev/v1
kind: Trigger
metadata:
  name: telegram-oncall
  labels:
    platform: telegram
    purpose: oncall

spec:
  type: Telegram
  config:
    # Event types
    events:
      - message
      - command

    # Specific chat/group IDs (optional)
    # chats:
    #   - -1001234567890  # SRE on-call group

    # Allowed users (Telegram user IDs) - optional
    # users:
    #   - 123456789   # On-call engineer 1

    # Authentication (env var reference)
    bot_token: ${TELEGRAM_BOT_TOKEN}

  # Command bindings for this trigger
  commands:
    /agent:
      agent: devops
      description: "Switch to DevOps agent"

    /incident:
      flow: incident-flow
      description: "Start incident response workflow"

    /status:
      agent: k8s-ops
      description: "Check system status"

    /diagnose:
      fleet: rca-fleet
      description: "Root cause analysis"

  # Default agent for natural language messages
  default_agent: devops
